
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  // Use direct PostgreSQL connection (not Prisma Cloud/Accelerate)
  datasource: {
    url: env("DATABASE_URL"),
    directUrl: env("DATABASE_URL"), // Use same URL for direct connection
  },
});
